DROP TABLE IF EXISTS user_transaction CASCADE;

CREATE TABLE user_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    date DATE,
    amount FLOAT(24),
    category VARCHAR(255),
    vendor VARCHAR(255),
    type ENUM ('CARD','DIRECT_DEBIT', 'INTERNET'),

    PRIMARY KEY (id)
)